name: Add Embeddings Database

on:
  release:
    types: [published]


permissions:
  contents: write

jobs:
  embeddings_db:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Pull source
        uses: actions/checkout@v4.2.2
      - name: Add Embeddings to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ${{github.workspace}}
          gh release upload ${{github.event.release.tag_name}} data/factflip_embeddings.zip#factflip_embeddings-${{github.event.release.tag_name}}.zip
        shell: bash
