name: Release and Pip Package Action

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Create Semantic Release
        uses: matteo4diani/poetry-semantic-release@v0
        id: create-release
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pypi-token: ${{ secrets.PYPI_TOKEN }}
          python-version: 3.12
      - name: Add Embeddings to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ${{github.workspace}}
          gh release upload "${{steps.create-release.outputs.tag}}" data/factflip_embeddings.zip#factflip_embeddings-${{steps.create-release.outputs.version}}.zip
        shell: bash
    outputs:
      released: ${{ steps.create-release.outputs.released }}
      tag: ${{ steps.create-release.outputs.tag }}
      version: ${{ steps.create-release.outputs.version }}
